import Head from 'next/head'
import styles from '../styles/Home.module.css'
import StatusSection from '../component/StatusSection'
import { Container, Row, Col } from 'react-bootstrap'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <body>
        <Container>
          <Row>
            <div style={{padding:'10px', fontSize:'30px', margin:'30px 40px 30px 10px'}}>
              Dashboard name
            </div>
          </Row>
          <Row>
            <StatusSection></StatusSection>
          </Row>
        </Container>
        <div></div>
      </body>
    </div>
  )
}
